site_name: kopy
site_url: https://flynshue.github.io/test-operator
repo_url: https://github.com/flynshue/test-operator
repo_name: flynshue/test-operator
theme:
  name: material
  icon:
    # logo: fontawesome/solid/copy
    # logo: material/cloud-sync
    logo: octicons/package-dependents-16
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs
    # - navigation.instant
    # - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.copy
nav:
  - Overview: index.md
plugins:
  - search:
markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      anchorlink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
