---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.flynshue.io
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.flynshue.io
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - core.flynshue.io
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
