# This rule is not used by the project output-dir itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.flynshue.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: output-dir
    app.kubernetes.io/managed-by: kustomize
  name: configmap-admin-role
rules:
- apiGroups:
  - core.flynshue.io
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - core.flynshue.io
  resources:
  - configmaps/status
  verbs:
  - get
