apiVersion: core.flynshue.io/v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: output-dir
    app.kubernetes.io/managed-by: kustomize
  name: configmap-sample
spec:
  # TODO(user): Add fields here
